### ISSUE TITLE
OpenPMD to ASTRA format conversion

### ISSUE THREAD

**Issue by alexanatoly** [AngelFP/APtools#10]
Dear Developers,

Is it possible to convert the PIC simulation data, which is in OpenPMD format (FBPIC code), to ASTRA particle tracking code format ?

OR, in general, if I have particle data information:

(1) x-position
(2) y-position
(3) z-position
(4) Px, x-momentum
(5) Py, y-momentum
(6) Pz, z-momentum
(7) Particles weight

can it be converted to ASTRA format ?

Thanks,
Alex

**Comment by AngelFP** [comment]
Hi @alexanatoly, thanks for your interest.

You can convert a particle distribution from openPMD to ASTRA format using the code below. Let me know if you find any issues.

```python
from aptools.particle_distributions import read_distribution, save_distribution

# Read beam from openpmd file (e.g., from FBPIC)
beam = read_distribution('/path/to/file.h5', data_format='openpmd', species='species_name')

# Save to astra
save_distribution(beam, file_path='astra_beam.txt', data_format='astra')
```

**Comment by AngelFP** [comment]
For your second question, if you have the particle arrays, you can make a [particle distribution](https://github.com/AngelFP/APtools/blob/e38b9398189bd0648913a3f0d3960e8539450512/aptools/particle_distributions/particle_distribution.py#L6), for example:

```python
import scipy.constants as ct
from aptools.particle_distributions import ParticleDistribution, save_distribution

# Create elecron beam from arrays.
beam = ParticleDistribution(x, y, z, px, py, pz, w, q_species=-ct.e, m_species=ct.m_e)

# Save to astra
save_distribution(beam, file_path='astra_beam.txt', data_format='astra')
```

**Comment by alexanatoly** [comment]
Hi @AngelFP, thanks for the help. Both ways work perfectly !!

Thanks for the excellent tool you have developed for combining different codes. 

Best regards,
Alex

**Comment by AngelFP** [comment]
Glad to hear it worked!
