### ISSUE TITLE
Radiation spectrum with APtools

### ISSUE THREAD

**Issue by alexanatoly** [AngelFP/APtools#12]
Dear Developer, 

I am looking for a tool to calculate radiation spectrum of oscillating electron beam in wakefield etc. I think at the moment it is not possible to use APtools for it. However, it might be a helpful for users to add such capabilities. 

If APtools will undergo any future massive upgrade, with extended advanced functionalities, please take note of this feature request. 

Thanks,
Alex

**Comment by AngelFP** [comment]
Hi @alexanatoly , thanks for the interest and the suggestion. Perhaps you can have a look at https://github.com/hightower8083/synchrad. It might be able to do what you need.

**Comment by alexanatoly** [comment]
Hi @AngelFP , thanks for the synchrad link.
