### ISSUE TITLE
Diagnostic (energy spectrum)

### ISSUE THREAD

**Issue by dmargarone** [AngelFP/APtools#13]
Dear APtools developers,

I am Daniela from Pisa University. I came to know about APtools from one of my friend. It looks great to make diagnostics of electron beam with it. 
I have problem in making energy spectrum of the electron beam. I can make electron beam energy spectrum as Energy on X-axis and spectrum (arbitrary unit) on Y-axis. But I want to know how to make energy spectrum as done in many articles.
I mean I want to plot energy spectrum as charge per MeV (pC/MeV) and also energy spectrum as charge per MeV per micron (pC/MeV/μm). I am using FBPIC code.

Thanks in advance.
DM

**Comment by dmargarone** [comment]
Hi 
I tried the function:   **energy_spectrum(px, py, pz, w=None, bins=100):** given in data_analysis/beam_diagnostics
but this gives me the similar energy spectrum as I used to make. I would appreciate if someone could let me know how to make energy spectrum in pC/MeV and pC/MeV/μm.

**Comment by AngelFP** [comment]
Hi Daniela,
If you make a histogram of the macroparticle energy using the charge as weight, then your energy spectrum will be in units of charge. Then, to get it in charge per energy you simply have to divide by the width of your bins.

An (untested) example:
```python
gamma = np.sqrt(1 + px**2 + py**2 + pz**2)
ene_hist, bin_edges = np.histogram(gamma, bins=100, weights=w)
# Convert from C to pC/MeV
ene_hist *= 1e12 / (bin_edges[1] - bin_edges[0])
```

**Comment by dmargarone** [comment]
Dear Professor Angel, 
Thank you for help. It was so straight forward, I didn't even thought about it. Thank you so much.
Just one more small discussion point : I think the number of bins should be of 1 MeV interval size, then only it will be really "pC/MeV".

I made small change in the above code lines:

dE = 1.0
Eref = E_min
Eind = 0
while Eref <= E_max: 
      Eref = Eref + dE    # energy interval of 1 MeV 
      Eind = Eind + 1

print("Optimun E bins = ", Eind)

**Now used this Wind in your give piece of code :**

gamma = np.sqrt(1 + px**2 + py**2 + pz**2)
ene_mev = gamma * 0.511
ene_hist, bin_edges = np.histogram(ene_mev, bins=**Eind**, weights=w)
# Convert from C to pC/MeV
ene_hist *= 1e12 / (bin_edges[1] - bin_edges[0])

**Do you think this way of selecting bins is correct ? **

**Comment by AngelFP** [comment]
Hi @dmargarone ,
There is no need to make the bins 1 MeV in width. They can be bigger or smaller than that. As long as you divide the bin charge over the bin width you will have the correct result. You can test that by plotting on top of each other several spectra that have a different bin size. The only difference will be that the smaller the bins, the more detailed the spectrum will be (until you no longer have enough particles per bin).

**Comment by dmargarone** [comment]
Dear Professor Angel,
I made plots with different bin size and found that pC/MeV changes with changing bin size. See the attached plots.
I did as follows:

```python
	plt.clf()	
	
	axs = plt.subplot(1,1,1)
	
	binI = 30    # initial bin number
	binF = 120   # final bin number
	
	while binI <= binF:
		E_hist, E_bins = np.histogram(E, bins=binI, weights=PQEar)
		E_hist *= 1.0e12 / (E_bins[1] - E_bins[0])
		#
		axs.plot(E_bins[:-1], E_hist, linewidth=1)
		binI = binI + 10
```

![Energy_per_MeV_zoom](https://github.com/AngelFP/APtools/assets/88077574/2ce69a0b-c262-4f8f-9156-71557f8bdb96)

![Energy_per_MeV](https://github.com/AngelFP/APtools/assets/88077574/866036f8-5c18-4c31-8f33-37019cabda36)

**Comment by AngelFP** [comment]
That looks good. As I said, when you make the bins smaller you are able to see more fine details in your spectrum. Ideally, you want your bins to be as small as possible. In practice, this is limited by the number of particles in your distribution, because if you don't have enough particles per bin the histogram will become noisy.
